### ISSUE TITLE
ビルドするとindex.htmlに記事の一覧が表示されない

### ISSUE THREAD

**Issue by masebb** [mira-tech/Hugo-blog#1]
`env HUGO_ENV="DEV" hugo server --watch --buildDrafts=true --buildFuture=true -t robust`
 (DEVモード)でLocalhostに立ててやる時だけ行ける
`hugo server`とか`hugo`でビルドとかしようとする時だけ一覧が表示されない

**Comment by peaceiris** [comment]
clone してみたのですが、Hugo 0.53 だと `hugo` も実行できないですね。

@mira-gfx 利用している Hugo のバージョンはいくつですか？

**Comment by masebb** [comment]
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.11.4"

どれ載せせればいいか分からないから`hugo env`で出てきたやつ全部載せ

**Comment by peaceiris** [comment]
@mira-gfx 
0.53 ですね。ありがとうございます。

まず、

https://github.com/mira-gfx/Hugo-blog/blob/5b68b55c02f92623f287e3713ea6ae4a56c3098c/saltandsugar.tech/layouts/_default/baseof.html#L15
https://github.com/mira-gfx/Hugo-blog/blob/5b68b55c02f92623f287e3713ea6ae4a56c3098c/saltandsugar.tech/layouts/_default/baseof.html#L16

この書き方だと Hugo 0.53 ではダメなのでまずこれを修正する必要があります。

#2 👈で対応します。

**Comment by mira-gfx** [comment]
hugo0.52に下げたほうが早いですかね？

**Comment by peaceiris** [comment]
#2 をマージしたら、

```
hugo server -D
```

を実行して、`http://localhost:1313/` にアクセスすると次のように記事一覧がでるはずです。

<img width="861" alt="screen shot 2019-01-13 at 20 41 22" src="https://user-images.githubusercontent.com/30958501/51084829-c1b42f80-1773-11e9-8167-c48d03f13556.png">

**Comment by masebb** [comment]
あ、どうも

**Comment by masebb** [comment]
うわああああああああああ
ありがとうございます！！！

**Comment by masebb** [comment]
![2019-01-13 20 49 18](https://user-images.githubusercontent.com/30523995/51084880-be6d7380-1774-11e9-90ff-907b24717caf.png)
